---
title: Apresentação sobre o código de taxa metabólica basal (TMB)
author: Beatriz Salles and Rafaely Reis
slideNumber: 5
format: revealjs
transition: slide

---

# Calculadora de TMB: Explicação do Código

---

## Função `calcular_tmb`

<div style="font-size: 0.8em;">
def calcular_tmb(peso, altura, idade, sexo): <p>
    if sexo == "masculino": <p>
        tmb = 66 + (13.7 * peso) + (5 * altura) - (6.8 * idade) <p>
    elif sexo == "feminino":<p>
        tmb = 665 + (9.6 * peso) + (1.8 * altura) - (4.7 * idade)<p>
    else: <p>
        tmb = None <p>
        print("Sexo não reconhecido.") <p>
    return tmb <p>
</div>

<p>A função calcular_tmb calcula a Taxa de Metabolismo Basal (TMB) usando a equação de Harris-Benedict.

---

## Função `calcular_macronutrientes`

 def calcular_macronutrientes(peso): <p>
    prot = 2 * peso <p>
    carb = 3 * peso <p>
    gord = 0.5 * peso <p>
    return prot, carb, gord <p>
<p>

A função calcular_macronutrientes calcula a quantidade de proteína, carboidratos e gorduras em gramas com base no peso do usuário.

---

## Função `calcular_gasto_calorico`

<div style="font-size: 0.7em;">
def calcular_gasto_calorico(exercicio, peso, tempo): <p>
    if exercicio == 1: <p>
        return 3.5 * peso * tempo <p>
    elif exercicio == 2: <p>
        return 6 * peso * tempo <p>
    elif exercicio == 3: <p>
        print("Saindo do programa!") <p>
        sys.exit() <p>
    else: <p>
        print("Exercício não reconhecido.") <p>
        return None <p>
</div>
<p>
A função calcular_gasto_calorico calcula o gasto calórico com base no tipo de exercício, peso do usuário e tempo de prática.

---

## Função `main`

    #Main Vai fazer as perguntas ao usuario
    def main():
    # Captura de dados do usuário
    peso = float(input("Digite seu peso (em kg): "))
    altura = float(input("Digite sua altura (em centimetros): "))
    idade = float(input("Digite sua idade: "))
    sexo = input("Digite seu sexo (masculino/feminino): ").lower()

    # Cálculo da TMB
    tmb = calcular_tmb(peso, altura, idade, sexo)

    if tmb is not None:
        # Exibição da TMB
        print(f"Sua taxa de metabolismo basal é {tmb:.2f} calorias.")

        # Cálculo de macronutrientes
        prot, carb, gord = calcular_macronutrientes(peso)
        print(f"Para atender suas necessidades diárias, consuma {prot:.2f}g de proteína, {carb:.2f}g de carboidratos e {gord:.2f}g de gordura.")

        # Captura de dados de exercício
        print("Digite o número do exercício que você pratica:")
        print("1 - Musculação média")
        print("2 - Musculação alta")
        print("3 - Não pratico nenhum desses exercícios / Sair")
        exercicio = int(input("Digite o numero do exercício desejado: "))
        tempo = float(input("Por quanto tempo você pratica essa atividade em horas: "))
        gasto_calorico = calcular_gasto_calorico(exercicio, peso, tempo)

        # Exibição do gasto calórico
        if gasto_calorico is not None:
            if exercicio == 1:
                print(f"Durante {tempo} horas de Musculação média, você queimou {gasto_calorico:.2f} calorias.")
            elif exercicio == 2:
                print(f"Durante {tempo} horas de Musculação alta, você queimou {gasto_calorico:.2f} calorias.")
        else:
            print("Exercício não reconhecido.")
    else:
        print("Não foi possível calcular a TMB. Verifique os dados fornecidos.")

        if __name__ == "__main__":
    main()

<div style="font-size: 0.8em;">
Nosso código irá fazer perguntas ao usuário relacionado ao seu peso, altura, idade e sexo. <p>
Com base nisso irá calcular sua taxa metabólica basal<p>
Retornando com a quantidade de macronutrientes que você precisa ingerir no dia. <p>
</div>


